#adding Routing
spring.cloud.gateway.routes[0].id=department
spring.cloud.gateway.routes[0].uri=lb://department
spring.cloud.gateway.routes[0].predicates[0]=Path=/department/**

#adding Routing
spring.cloud.gateway.routes[1].id=Employee
spring.cloud.gateway.routes[1].uri=lb://Employee
spring.cloud.gateway.routes[1].predicates[0]=Path=/employee/**

spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=Employee
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/employee


resilience4j.circuitbreaker.instances.Employee.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.Employee.slidingWindowSize=6
resilience4j.circuitbreaker.instances.Employee.failureRateThreshold=50
resilience4j.circuitbreaker.instances.Employee.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.Employee.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.Employee.minimumNumberOfCalls=5
