#adding Routing
spring.cloud.gateway.routes[0].id=department
spring.cloud.gateway.routes[0].uri=lb://department
spring.cloud.gateway.routes[0].predicates[0]=Path=/department/**

#adding Routing
spring.cloud.gateway.routes[1].id=Employee
spring.cloud.gateway.routes[1].uri=lb://Employee
spring.cloud.gateway.routes[1].predicates[0]=Path=/employee/**
